New log file opened at Sun Jan 03 11:36:38 CET 2016 by 10428@Obsidian
Taking next connection to: 53845
New client attempting to connect on port: 53846-53845
  Address = /192.168.178.14:53845
This client on port 53846 has uuid 72b43f96-91b8-4051-9a63-2b852a1c159f configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-72b43f96-91b8-4051-9a63-2b852a1c159f
Taking next connection to: 53845
New client attempting to connect on port: 53847-53845
  Address = /192.168.178.14:53845
Handshake exception on socket: 53847
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 53845
New client attempting to connect on port: 53848-53845
  Address = /192.168.178.14:53845
This client on port 53848 has uuid 1cf77749-e227-4292-9f22-0c11180ebe28 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-72b43f96-91b8-4051-9a63-2b852a1c159f, activator-1cf77749-e227-4292-9f22-0c11180ebe28
Taking next connection to: 53845
New client attempting to connect on port: 53858-53845
  Address = /192.168.178.14:53845
Handshake exception on socket: 53858
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 53845
New client attempting to connect on port: 53859-53845
  Address = /192.168.178.14:53845
This client on port 53859 has uuid e2701194-d490-4865-8518-dbb25e7e72aa configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-72b43f96-91b8-4051-9a63-2b852a1c159f, play-fork-run-e2701194-d490-4865-8518-dbb25e7e72aa
Taking next connection to: 53845
Checking to see if clients are empty...
No non-daemon clients connected after 3 min. Shutting down.
Server socket thread exiting.
0 clients open, will close them...
All client sockets have been closed.
Closing the 10428@Obsidian logs at Sun Jan 03 11:42:09 CET 2016, goodbye.
