New log file opened at Mon Oct 05 14:24:17 CEST 2015 by 4604@PC-14874
Taking next connection to: 49814
New client attempting to connect on port: 49815-49814
  Address = /139.63.20.189:49814
This client on port 49815 has uuid 6b2f05d5-88f7-4bdd-bccd-52002ffea411 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-6b2f05d5-88f7-4bdd-bccd-52002ffea411
Taking next connection to: 49814
New client attempting to connect on port: 49816-49814
  Address = /139.63.20.189:49814
Handshake exception on socket: 49816
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49814
New client attempting to connect on port: 49817-49814
  Address = /139.63.20.189:49814
This client on port 49817 has uuid 032731e2-5748-488e-b15e-a6b825b73762 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-6b2f05d5-88f7-4bdd-bccd-52002ffea411, activator-032731e2-5748-488e-b15e-a6b825b73762
Taking next connection to: 49814
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49814
New client attempting to connect on port: 49842-49814
  Address = /139.63.20.189:49814
Handshake exception on socket: 49842
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 49814
New client attempting to connect on port: 49843-49814
  Address = /139.63.20.189:49814
This client on port 49843 has uuid aeb62e8a-d949-47b9-8e3d-33a8aa34c2e3 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-032731e2-5748-488e-b15e-a6b825b73762, play-fork-run-aeb62e8a-d949-47b9-8e3d-33a8aa34c2e3
Taking next connection to: 49814
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49814
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 49814
