New log file opened at Mon Oct 05 12:51:10 CEST 2015 by 6488@PC-14874
Taking next connection to: 59038
New client attempting to connect on port: 59039-59038
  Address = /139.63.20.189:59038
This client on port 59039 has uuid 4bfa4a73-4e51-4fd9-a28c-5a78bcb1f9d4 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-4bfa4a73-4e51-4fd9-a28c-5a78bcb1f9d4
Taking next connection to: 59038
New client attempting to connect on port: 59040-59038
  Address = /139.63.20.189:59038
Handshake exception on socket: 59040
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 59038
New client attempting to connect on port: 59041-59038
  Address = /139.63.20.189:59038
This client on port 59041 has uuid 907a4b65-7ded-4b86-a921-2f5538c807e6 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-4bfa4a73-4e51-4fd9-a28c-5a78bcb1f9d4, activator-907a4b65-7ded-4b86-a921-2f5538c807e6
Taking next connection to: 59038
New client attempting to connect on port: 59062-59038
  Address = /139.63.20.189:59038
Handshake exception on socket: 59062
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:265)
	at java.io.DataInputStream.readInt(DataInputStream.java:387)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 59038
New client attempting to connect on port: 59063-59038
  Address = /139.63.20.189:59038
This client on port 59063 has uuid dc214d3b-5efa-4f4e-8be0-50793e3a5409 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-907a4b65-7ded-4b86-a921-2f5538c807e6, play-fork-run-dc214d3b-5efa-4f4e-8be0-50793e3a5409
Taking next connection to: 59038
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 59038
