New log file opened at Thu Nov 19 16:06:35 CET 2015 by 1284@Obsidian
Taking next connection to: 57385
New client attempting to connect on port: 57386-57385
  Address = /192.168.178.14:57385
This client on port 57386 has uuid 6c628a04-90cc-4d90-9ecf-39309f893b36 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-6c628a04-90cc-4d90-9ecf-39309f893b36
Taking next connection to: 57385
New client attempting to connect on port: 57387-57385
  Address = /192.168.178.14:57385
Handshake exception on socket: 57387
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 57385
New client attempting to connect on port: 57388-57385
  Address = /192.168.178.14:57385
This client on port 57388 has uuid a23795bd-3365-4a7a-be79-cc188f82bc02 configName activator humanReadableName Activator protocolVersion 3 featureTags Vector()
Connected Clients: activator-6c628a04-90cc-4d90-9ecf-39309f893b36, activator-a23795bd-3365-4a7a-be79-cc188f82bc02
Taking next connection to: 57385
New client attempting to connect on port: 57389-57385
  Address = /192.168.178.14:57385
Handshake exception on socket: 57389
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 57385
New client attempting to connect on port: 57390-57385
  Address = /192.168.178.14:57385
This client on port 57390 has uuid 3a72bc1a-a6d2-42e7-8d0e-41d72109c256 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-6c628a04-90cc-4d90-9ecf-39309f893b36, activator-a23795bd-3365-4a7a-be79-cc188f82bc02, play-fork-run-3a72bc1a-a6d2-42e7-8d0e-41d72109c256
Taking next connection to: 57385
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 57385
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 57385
