New log file opened at Mon Jun 15 12:42:39 CEST 2015 by 4176@PC-14874
Taking next connection to: 58580
New client attempting to connect on port: 58582-58580
  Address = /139.63.20.117:58580
This client on port 58582 has uuid f1e77bfc-b85c-4328-9ce0-39344e5e288d configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-f1e77bfc-b85c-4328-9ce0-39344e5e288d
Taking next connection to: 58580
New client attempting to connect on port: 58583-58580
  Address = /139.63.20.117:58580
Handshake exception on socket: 58583
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 58580
New client attempting to connect on port: 58584-58580
  Address = /139.63.20.117:58580
This client on port 58584 has uuid ce951ae0-d350-4a30-aca8-2de7e7c6090c configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-f1e77bfc-b85c-4328-9ce0-39344e5e288d, activator-ce951ae0-d350-4a30-aca8-2de7e7c6090c
Taking next connection to: 58580
New client attempting to connect on port: 58589-58580
  Address = /139.63.20.117:58580
Handshake exception on socket: 58589
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 58580
New client attempting to connect on port: 58590-58580
  Address = /139.63.20.117:58580
This client on port 58590 has uuid 7d6af3cf-4ee9-4197-9fce-4a74eff1c684 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-ce951ae0-d350-4a30-aca8-2de7e7c6090c, play-fork-run-7d6af3cf-4ee9-4197-9fce-4a74eff1c684
Taking next connection to: 58580
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 58580
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 58580
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 58580
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 58580
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 58580
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 58580
