New log file opened at Wed May 27 15:17:56 CEST 2015 by 5492@PC-14874
Taking next connection to: 59724
New client attempting to connect on port: 59725-59724
  Address = /139.63.20.190:59724
This client on port 59725 has uuid 66a1e8d0-97c9-40fd-95b6-5835db3c3bec configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-66a1e8d0-97c9-40fd-95b6-5835db3c3bec
Taking next connection to: 59724
New client attempting to connect on port: 59726-59724
  Address = /139.63.20.190:59724
Handshake exception on socket: 59726
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 59724
New client attempting to connect on port: 59727-59724
  Address = /139.63.20.190:59724
This client on port 59727 has uuid 017ce6a8-0b8d-4497-b733-50d666c72858 configName activator humanReadableName Activator protocolVersion 1 featureTags Vector()
Connected Clients: activator-66a1e8d0-97c9-40fd-95b6-5835db3c3bec, activator-017ce6a8-0b8d-4497-b733-50d666c72858
Taking next connection to: 59724
New client attempting to connect on port: 59765-59724
  Address = /139.63.20.190:59724
Handshake exception on socket: 59765
sbt.impl.ipc.HandshakeException: Unable to perform handshake
	at sbt.impl.ipc.Peer.handshake(IPC.scala:46)
	at sbt.impl.ipc.MultiClientServer.<init>(IPC.scala:150)
	at sbt.server.SbtServerSocketHandler$$anon$1.run(SbtServerSocketHandler.scala:43)
Caused by: java.net.SocketException: Software caused connection abort: recv failed
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at java.io.BufferedInputStream.fill(Unknown Source)
	at java.io.BufferedInputStream.read(Unknown Source)
	at java.io.DataInputStream.readInt(Unknown Source)
	at sbt.impl.ipc.Peer.receive(IPC.scala:95)
	at sbt.impl.ipc.Peer.handshake(IPC.scala:49)
	... 2 more
Taking next connection to: 59724
New client attempting to connect on port: 59766-59724
  Address = /139.63.20.190:59724
This client on port 59766 has uuid 88226e07-06cb-42c9-93f5-19df59b12ce6 configName play-fork-run humanReadableName Play Fork Run protocolVersion 1 featureTags Vector()
Connected Clients: activator-017ce6a8-0b8d-4497-b733-50d666c72858, play-fork-run-88226e07-06cb-42c9-93f5-19df59b12ce6
Taking next connection to: 59724
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 59724
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 59724
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 59724
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 59724
Checking to see if clients are empty...
We have 1 non-daemon clients, continuing serving connections.
Taking next connection to: 59724
